name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

defaults:
  run:
    shell: bash
    working-directory: "./backend"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

  lint:
    name: Run lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false

      - name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.54"
